version: '3.7'
services:
  nodejs:
    image: node:14
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - db
    user: "1000:1000"
    ports:
      - "1337:1337"
  db:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "zeus"
      MYSQL_PASSWORD: "zeus"
      MYSQL_DATABASE: "zeus"
    volumes:
      - "./.docker/storage/mysql:/var/lib/mysql"